### ISSUE TITLE
Doesn't work withPandas dataframes

### ISSUE THREAD

**Issue by MovsisyanM** [soroushj/keras-balanced-batch-generator#5]
Doesn't with Pandas dataframes, and doesnt throw an exception when a pandas df is given to init

**Comment by soroushj** [comment]
Thanks for reporting this issue. I'll release a new version that will raise a clear error when `x` or `y` is not a NumPy array. You can convert a Pandas DataFrame to a NumPy array using [`pandas.DataFrame.to_numpy`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_numpy.html).
